CFLAGS=-ggdb -Wall -std=c11
LDLIBS=-lm

all:
	zadanie_5 tab4 zadanie_6 tab5 zadanie_4 zadanie_1 zadanie_2 zadanie_3 tab6 zadanie_11

clean :
	rm -f *.o zadanie_5 tab4 zadanie_6 tab5 zadanie_4 zadanie_1 zadanie_2 zadanie_3 tab6 zadanie_11